name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:11.7.1-devel-ubuntu22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y gcc gfortran

    - name: Build library and test
      run: make

    - name: Run tests
      run: make test
